### PR TITLE
Field errors

### PR DESCRIPTION
**Pull request by grilix**
This enables Luca to display server-returned errors on form fields. Please tell me what your thought is about this approach.

We've seen that Field already have `statuses`:

``` coffee
statuses: [
  "warning"
  "error"
  "success"
]
```

That `statuses` looks related but we were not really sure, because a child could remove its support for errors, and that is not what we want, or is it?

### CODE REVIEW

**Comment by datapimp** [comment]
The statuses match the control group 'Form Control States' defined here:

http://twitter.github.com/bootstrap/base-css.html#forms

**Comment by datapimp** [comment]
Are you familiar with the jasmine test suite yet? We should write tests for this behavior

**Comment by grilix** [comment]
I'm not very familiar with Jasmine, how do you think I can start?
Yes, it should be field_errors, I'll change it.

**Comment by datapimp** [comment]
Thank you Gonzalo for your contribution.

**Pull request merged**
